name = "alfred"
main = "src/index.ts"
compatibility_date = "2025-11-01"
compatibility_flags = ["nodejs_compat"]

[[routes]]
pattern = "alfred.raylin.cc"
custom_domain = true

[[kv_namespaces]]
binding = "ALFRED_KV"
id = "1a7640431a8642239223d4243b55f375"
